/* ----------------------------------------------------------
                     HAXBALL TOOLS 54-365
                       BY TLS / Teeleese
----------------------------------------------------------- */

const quickChat = {

    10: "Great shot! 🎯",
    11: "Well played! 👏",
    12: "Nice play! ⚡",
    13: "Insane speed! 🏃💨",
    14: "What a pass! 🎁",
    15: "Smart move! 🧠",
    16: "Beautiful touch! ✨",
    17: "Clean play! 🧼",
    18: "Perfect timing! ⏰",
    19: "Respect! 🤝",
    20: "Playing with slippers? 🩴",
    21: "Wake up bro 😴",
    22: "That was cute 😂",
    23: "Did you even try? 🤨",
    24: "Nice miss 😹",
    25: "My uncle shoots better! 👴⚽",
    26: "You sleeping? 🛌",
    27: "Even my dog plays better 🐶",
    28: "Zero aim 🎯❌",
    29: "Bro tripping 💀",
    30: "Big F! 🕳️",
    31: "Lost in space? 🌌",
    32: "Straight from the circus 🤡",
    33: "Tragic 😭",
    34: "You good? 😅",
    35: "Comedy mode 🎭",
    36: "Oopsie 😂",
    37: "Rookie mistake 🍼",
    38: "Controller disconnected 🎮❌",
    39: "McDonald's WiFi 🍟📶",
    40: "Still hurts? 😏",
    41: "Stay salty 🧂",
    42: "Don’t cry 😢",
    43: "Try harder 🔧",
    44: "Playing half-naked? 🩲",
    45: "That's embarrassing 😬",
    46: "You’re folding 🧻",
    47: "Bro cooked himself 🍳",
    48: "Clown spotted 🤡",
    49: "Skill issue 💀",
    50: "WHAT A GOAL! 🚀🔥",
    51: "Too easy 😎",
    52: "Clean finish 🧽⚽",
    53: "We cooking 🍳🔥",
    54: "Let’s gooo! 🎉",
    55: "I’M THE BOSS 👑",
    56: "Unstoppable 💥",
    57: "Top shelf ❄️⚽",
    58: "Elite play 🛡️",
    59: "MVP MODE ⭐",
    60: "Stop stealing plays 😡",
    61: "Bro what was that 😭",
    62: "Lag is insane 🌐🐢",
    63: "This game hates me 💔",
    64: "Unfair bro 😤",
    65: "Unbelievable 😩",
    66: "I’m losing it 🤯",
    67: "Impossible 😵",
    68: "No way 😱",
    69: "Pain. Pure pain 😔",
    70: "Turbo mode ⚡",
    71: "GG easy 😎",
    72: "Pizza > Football 🍕⚽",
    73: "Certified moment 📜",
    74: "Bro thinks he’s HIM 😂",
    75: "Cosmic vibes 🌌",
    76: "Overthinking detected 🧩",
    77: "We vibin’ 🎶",
    78: "Showtime! 🎬",
    79: "Maximum overdrive 🚗💨",
    80: "Was that even legal? 🚔",
    81: "Delete the game 🗑️",
    82: "Lag IRL too? 🤖",
    83: "Try uninstalling 😭",
    84: "Bot behavior 🤖💀",
    85: "Hard throw 💣",
    86: "Rebooting… 🔄",
    87: "NPC detected 🧍",
    88: "Pray for WiFi 🙏📶",
    89: "That was a crime 💀",
    90: "Smooth play 🧊",
    91: "Cold finish ❄️⚽",
    92: "Professional move 📘",
    93: "Nice control 🎮",
    94: "Clean shot ✨",
    95: "Good teamwork 🤝",
    96: "Solid defense 🛡️",
    97: "Textbook play 📚",
    98: "Good effort 👍",
    99: "You’re improving 🔥",
    100: "Random powers activated ✨",
    101: "Ultra instinct mode 🌀",
    102: "Brain loading… ⏳",
    103: "Certified chaos 💥",
    104: "That's wild 🤯",
    105: "Galactic energy 🌠",
    106: "You summoned me? 🧙",
    107: "Quantum move ⚛️",
    108: "Error 404: Skill not found 🔍",
    109: "AI takeover 🤖",
    110: "Mega fail 💥😂",
    111: "Bro vanished 🫥",
    112: "You glitching? 🧩",
    113: "Unlocked new bug 🐛",
    114: "Simulation breaking 🧨",
    115: "Matrix moment 🟩",
    116: "Alternate timeline 🌐",
    117: "Lucky bounce 🍀⚽",
    118: "Unexpected W 🙌",
    119: "Chaos approved 😈",
    120: "Galaxy brain play 🧠🌌",
    121: "Stealth mode 🥷",
    122: "That escalated fast ⚡",
    123: "Bro teleported 🌀",
    124: "Physics denied 🚫⚛️",
    125: "Certified glitch 🎛️",
    126: "Out of nowhere 😳",
    127: "Perfect chaos 🌪️",
    128: "Comedy peak 😂🔥",
    129: "Absolute madness 🤪",
    130: "Ultra combo 🥋🔥",
    131: "Max efficiency ⚙️",
    132: "Impossible dodge 🌀",
    133: "Shadow clone jutsu 👥",
    134: "You levitating? 🛸",
    135: "Dimensional shift 🌌",
    136: "Cosmic disaster ☄️",
    137: "Juked into another realm 🚪",
    138: "That wasn’t human 🤖",
    139: "Certified highlight 🎞️",
    140: "Epic moment 🎇",
    141: "Supercharge ⚡⚡",
    142: "Break the limits 🚀",
    143: "Reality bending 🪄",
    144: "Boss level unlocked 👑",
    145: "Peak performance 🧗",
    146: "Legendary move 🏆",
    147: "This is art 🎨",
    148: "Epic fail 😂💀",
    149: "Universe approves 🌍✨"
};

room.onPlayerChat = function(player, message) {

    const match = message.trim().match(/^(\d{2,3})/);

    if (match) {
        const code = match[1];

        if (quickChat[code]) {
            room.sendChat(quickChat[code], player.id);
            return false; 
        }
    }
    return true;
};
